package com.example.wp4u.database.model

import androidx.room3.ColumnInfo
import androidx.room3.Entity
import androidx.room3.ForeignKey
import androidx.room3.PrimaryKey
import androidx.room3.Index

/**
 * Image on the vision board.
 *
 * The image file itself lives in the app's internal storage; only its
 * absolute path is stored here. This matches the Demo 2 design decision
 * (files on disk, paths in the database) and keeps the DB small and fast.
 *
 * Two foreign keys tie each image to an owning [User] and a parent [Category], which
 * is what makes boards user-specific: an image belongs to one person's copy of one
 * category, not to a single shared board. Both foreign key columns are indexed so
 * "all images in this category for this user" stays fast as the table grows.
 *
 * @property imagePK primary key of the image, generated by Room on insert.
 * @property userFK id of the [User] who owns this image.
 * @property categoryFK id of the [Category] this image is filed under (1-5).
 * @property filePath ABSOLUTE path to the file in internal storage, produced at
 *                    runtime by `ImageStorage.copyToInternalStorage()` and rendered by
 *                    `ImageAdapter` via `Glide.load(File(filePath))`. It is stored as an
 *                    absolute path because a path fixed at build time would not resolve
 *                    on any given install.
 * @property displayOrder position of the image within its board.
 * @property uploadedAt timestamp of when the image was added, stored as a Unix epoch
 *                      value in milliseconds (`Long`).
 */
@Entity(tableName = "IMAGE",
    indices = [Index("user_fk"), Index("category_fk")],
    foreignKeys = [
        ForeignKey(
            entity = User::class,
            childColumns = ["user_fk"],
            parentColumns = ["userPK"]
        ),
        ForeignKey(
            entity = Category::class,
            childColumns = ["category_fk"],
            parentColumns = ["categoryPK"]
        )])
data class Image(
    @PrimaryKey(autoGenerate = true) val imagePK: Int = 0,
    @ColumnInfo(name = "user_fk") val userFK: Int,
    @ColumnInfo(name = "category_fk") val categoryFK: Int,
    @ColumnInfo(name = "file_path") val filePath: String,
    @ColumnInfo(name = "display_order") val displayOrder: Int, // will support reorder feature in pt 4 (0-based)
    @ColumnInfo(name = "uploaded_at") val uploadedAt: Long,
)