package com.example.wp4u.database.model

import androidx.room3.ColumnInfo
import androidx.room3.Entity
import androidx.room3.PrimaryKey

/**
 * User account to keep user activity across devices.
 *
 * Room entity mapped to the `USER` table. A user row is created by
 * [com.example.wp4u.data.AuthRepository] when someone registers on the
 * [com.example.wp4u.ui.accounts.CreateAccount] screen.
 *
 * [userPK] is the anchor for the whole per-user design: every row in the `IMAGE`
 * table points back here through its `user_fk` foreign key, so each account sees only
 * its own vision boards.
 *
 * @property userPK primary key of the user, generated by Room on insert.
 * @property username login name; also what the user types on the sign-in screen.
 * @property email address supplied at registration and checked for duplicates
 *                 before a new account is accepted.
 * @property passwordHash hashed password. The plain-text password is never stored.
 * @property createdAt timestamp of account creation, stored as a Unix epoch value in
 *                     milliseconds (`Long`) because SQLite has no native date type.
 */
@Entity(tableName = "USER")
data class User(
    @PrimaryKey(autoGenerate = true) val userPK: Int = 0,
    @ColumnInfo(name = "username") val username: String,
    @ColumnInfo(name = "email") val email: String,
    @ColumnInfo(name = "password_hash") val passwordHash: String,
    @ColumnInfo(name = "created_at") val createdAt: Long
)