package com.example.wp4u.database.dao

import com.example.wp4u.database.model.User
import androidx.room3.Dao
import androidx.room3.Insert
import androidx.room3.OnConflictStrategy
import androidx.room3.Query

/**
 * User data access object.
 *
 * Used to insert new users; Update existing users; Delete users; Select a user.
 *
 * Room generates the implementation of this interface at build time from the
 * annotations below (via KSP). Every method is a `suspend` function so that database
 * work is forced off the main thread; callers reach this DAO through
 * [com.example.wp4u.data.AuthRepository] rather than using it directly.
 */
@Dao
interface UserDAO {

    /**
     * Inserts a newly registered account.
     *
     * Uses [OnConflictStrategy.ABORT] so a clashing row raises an exception instead of
     * silently overwriting an existing account.
     *
     * @param user the account to store; its `userPK` is ignored and generated by Room.
     * @return the generated primary key of the inserted row.
     */
    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insertUser(user: User): Long //Adds newly created user account

    /**
     * Looks up an account by username and password — the sign-in path used by
     * [com.example.wp4u.ui.accounts.Login].
     *
     * @param username the username typed on the sign-in screen.
     * @param passwordHash the hashed password to match against the stored hash.
     * @return the matching [User], or `null` if the credentials are not valid.
     */
    @Query("SELECT * FROM USER WHERE username=:username AND password_hash=:passwordHash")
    suspend fun getUserByUserPass(username: String, passwordHash: String): User? //Gets single user account (by username and password).

    /**
     * Looks up an account by email and password, allowing sign-in with either
     * identifier.
     *
     * @param email the email address registered to the account.
     * @param passwordHash the hashed password to match against the stored hash.
     * @return the matching [User], or `null` if the credentials are not valid.
     */
    @Query("SELECT * FROM USER WHERE email=:email AND password_hash=:passwordHash")
    suspend fun getUserByEmailPass(email: String, passwordHash: String): User? //Gets single user account (by email and password).

    /**
     * Checks whether an email address is already registered, so registration can be
     * rejected before a duplicate account is created.
     *
     * @param email the email address to look for.
     * @return the existing [User] if the email is taken, or `null` if it is free.
     */
    @Query("Select * FROM USER WHERE email=:email")
    suspend fun checkIfEmailExists(email: String): User? //Checks if email is already registered to account in database
}